// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
    about: dynamic(() => import("../blocks/About")),
    image: dynamic(() => import("./Image")),
    mega_hero: dynamic(() => import("./MegaHero")),
    project_gallery: dynamic(() => import("./ProjectGallery")),
    spacer: dynamic(() => import("./Spacer")),
    standout: dynamic(() => import("./Standout")),
    text: dynamic(() => import("./Text")),
    text_with_image: dynamic(() => import("./TextWithImage")),
    video: dynamic(() => import("./Video")),
};
