// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CategoryDocumentDataSlicesSlice =
  | VideoSlice
  | ImageSlice
  | TextWithImageSlice
  | ProjectGallerySlice;

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Title field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Category*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: category.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CategoryDocumentDataSlicesSlice> /**
   * Meta Title field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Robots field in *Category*
   *
   * - **Field Type**: Select
   * - **Placeholder**: all
   * - **API ID Path**: category.meta_robots
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  meta_robots: prismic.SelectField<"none" | "noindex" | "nofollow">;

  /**
   * Include in Sitemap field in *Category*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: category.sitemap
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  sitemap: prismic.BooleanField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

type ClientDocumentDataSlicesSlice = never;

/**
 * Content for Client documents
 */
interface ClientDocumentData {
  /**
   * Name field in *Client*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Client*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: client.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClientDocumentDataSlicesSlice>;
}

/**
 * Client document from Prismic
 *
 * - **API ID**: `client`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ClientDocumentData>, "client", Lang>;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Homepage field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.homepage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  homepage: prismic.LinkField;

  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type NotFoundDocumentDataSlicesSlice = TextWithImageSlice | ImageSlice;

/**
 * Content for Not Found documents
 */
interface NotFoundDocumentData {
  /**
   * Slice Zone field in *Not Found*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: not_found.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NotFoundDocumentDataSlicesSlice> /**
   * Meta Title field in *Not Found*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: not_found.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Not Found*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: not_found.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Not Found*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: not_found.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Not Found document from Prismic
 *
 * - **API ID**: `not_found`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NotFoundDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NotFoundDocumentData>,
    "not_found",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | VideoSlice
  | StandoutSlice
  | AboutSlice
  | ProjectGallerySlice
  | MegaHeroSlice
  | ImageSlice
  | TextWithImageSlice;

/**
 * Item in *Page → Footer*
 */
export interface PageDocumentDataFooterItem {
  /**
   * Show "Back To" Link field in *Page → Footer*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: page.footer[].show_back_to_link
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_back_to_link: prismic.BooleanField;

  /**
   * Link Back Label field in *Page → Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If left blank, will revert to the value specified under "Settings" for label and link
   * - **API ID Path**: page.footer[].link_back_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_back_label: prismic.KeyTextField;

  /**
   * Link Back field in *Page → Footer*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.footer[].link_back
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_back: prismic.ContentRelationshipField<"page" | "project">;
}

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Robots field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: all
   * - **API ID Path**: page.meta_robots
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  meta_robots: prismic.SelectField<"none" | "noindex" | "nofollow">;

  /**
   * Include in Sitemap field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: page.sitemap
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  sitemap: prismic.BooleanField /**
   * Footer field in *Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.footer[]
   * - **Tab**: Config
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  footer: prismic.GroupField<Simplify<PageDocumentDataFooterItem>>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Project → Categories*
 */
export interface ProjectDocumentDataCategoriesItem {
  /**
   * Category field in *Project → Categories*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.categories[].category
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;
}

/**
 * Item in *Project → Credits*
 */
export interface ProjectDocumentDataCreditsItem {
  /**
   * Title field in *Project → Credits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.credits[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Name field in *Project → Credits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.credits[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

type ProjectDocumentDataSlicesSlice =
  | SpacerSlice
  | VideoSlice
  | TextWithImageSlice
  | ImageSlice;

/**
 * Item in *Project → Footer*
 */
export interface ProjectDocumentDataFooterItem {
  /**
   * Show "Back To" Link field in *Project → Footer*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: project.footer[].show_back_to_link
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_back_to_link: prismic.BooleanField;

  /**
   * Link Back Label field in *Project → Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If left blank, will revert to the value specified under "Settings" for label and link
   * - **API ID Path**: project.footer[].link_back_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_back_label: prismic.KeyTextField;

  /**
   * Link Back field in *Project → Footer*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.footer[].link_back
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_back: prismic.ContentRelationshipField<"page" | "project">;
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Client field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  client: prismic.ContentRelationshipField<"client">;

  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Categories field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  categories: prismic.GroupField<Simplify<ProjectDocumentDataCategoriesItem>>;

  /**
   * Color field in *Project*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: project.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;

  /**
   * Hero Format field in *Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: The hero will display the default video
   * - **Default Value**: landscape
   * - **API ID Path**: project.hero_format
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  hero_format: prismic.SelectField<"landscape" | "portrait", "filled">;

  /**
   * Video Long field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This video will be displayed on the project page
   * - **API ID Path**: project.video_full
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_full: prismic.KeyTextField;

  /**
   * Placeholder Timestamp field in *Project*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Adjust the placeholder displayed on the project page (time in seconds)
   * - **API ID Path**: project.placeholder_timestamp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  placeholder_timestamp: prismic.NumberField;

  /**
   * Video Short - Default field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Default video used on galleries playing on hover
   * - **API ID Path**: project.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video: prismic.KeyTextField;

  /**
   * Video Short - Alternative field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Alternative video used on galleries playing on hover
   * - **API ID Path**: project.video_alternative
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_alternative: prismic.KeyTextField;

  /**
   * Credits field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.credits[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  credits: prismic.GroupField<Simplify<ProjectDocumentDataCreditsItem>>;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Robots field in *Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: all
   * - **API ID Path**: project.meta_robots
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  meta_robots: prismic.SelectField<"none" | "noindex" | "nofollow">;

  /**
   * Include in Sitemap field in *Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: project.sitemap
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  sitemap: prismic.BooleanField /**
   * Footer field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.footer[]
   * - **Tab**: Config
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  footer: prismic.GroupField<Simplify<ProjectDocumentDataFooterItem>>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Item in *Redirects → Redirects*
 */
export interface RedirectsDocumentDataRedirectsItem {
  /**
   * Source field in *Redirects → Redirects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Relative path
   * - **API ID Path**: redirects.redirects[].source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField;

  /**
   * Destination field in *Redirects → Redirects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Relative path
   * - **API ID Path**: redirects.redirects[].destination
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  destination: prismic.KeyTextField;

  /**
   * Permanent field in *Redirects → Redirects*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: redirects.redirects[].permanent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  permanent: prismic.BooleanField;
}

/**
 * Content for Redirects documents
 */
interface RedirectsDocumentData {
  /**
   * Redirects field in *Redirects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  redirects: prismic.GroupField<Simplify<RedirectsDocumentDataRedirectsItem>>;
}

/**
 * Redirects document from Prismic
 *
 * - **API ID**: `redirects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedirectsDocumentData>,
    "redirects",
    Lang
  >;

/**
 * Item in *Settings → Social Links*
 */
export interface SettingsDocumentDataSocialLinksItem {
  /**
   * Title field in *Settings → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Settings → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Footer "Back To" Link*
 */
export interface SettingsDocumentDataFooterBackToLinkItem {
  /**
   * Link Label field in *Settings → Footer "Back To" Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_back_to_link[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Footer "Back To" Link*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_back_to_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<"page">;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;

  /**
   * Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  >;

  /**
   * Footer "Back To" Link field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_back_to_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_back_to_link: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterBackToLinkItem>
  >;

  /**
   * Legal Mentions field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.legal_mentions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  legal_mentions: prismic.KeyTextField /**
   * Robots field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.robots
   * - **Tab**: Robots
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  robots: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | CategoryDocument
  | ClientDocument
  | NavigationDocument
  | NotFoundDocument
  | PageDocument
  | ProjectDocument
  | RedirectsDocument
  | SettingsDocument;

/**
 * Item in *About → Default → Primary → Contacts*
 */
export interface AboutSliceDefaultPrimaryContactsItem {
  /**
   * Title field in *About → Default → Primary → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.contacts[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Label field in *About → Default → Primary → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.contacts[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *About → Default → Primary → Contacts*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.contacts[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *About → Default → Primary → Footer*
 */
export interface AboutSliceDefaultPrimaryFooterItem {
  /**
   * Text field in *About → Default → Primary → Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.footer[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Link field in *About → Default → Primary → Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.footer[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Label field in *About → Default → Primary → Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.footer[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Color field in *About → Default → Primary → Footer*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.footer[].color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Text field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Contact Link Label field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.contact_link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_link_label: prismic.KeyTextField;

  /**
   * Contact Link field in *About → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.contact_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_link: prismic.LinkField;

  /**
   * Contacts field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.contacts[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contacts: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryContactsItem>>;

  /**
   * Footer field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.footer[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryFooterItem>>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Image → Smart → Primary → Images*
 */
export interface ImageSliceSmartPrimaryImagesItem {
  /**
   * Image field in *Image → Smart → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.smart.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Image → Smart → Primary → Layouts*
 */
export interface ImageSliceSmartPrimaryLayoutsItem {
  /**
   * Breakpoint field in *Image → Smart → Primary → Layouts*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: desktop
   * - **API ID Path**: image.smart.primary.layouts[].breakpoint
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  breakpoint: prismic.SelectField<"desktop" | "mobile", "filled">;

  /**
   * Columns field in *Image → Smart → Primary → Layouts*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: image.smart.primary.layouts[].columns
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  columns: prismic.SelectField<
    "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10",
    "filled"
  >;

  /**
   * Gutter field in *Image → Smart → Primary → Layouts*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: big
   * - **API ID Path**: image.smart.primary.layouts[].gutter
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  gutter: prismic.SelectField<"big" | "medium" | "small" | "none", "filled">;
}

/**
 * Item in *Image → Banner - Small x Big x Small → Primary → Images*
 */
export interface ImageSliceBannerSmallXBigXSmallPrimaryImagesItem {
  /**
   * Image field in *Image → Banner - Small x Big x Small → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.bannerSmallXBigXSmall.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Image → Banner - Big x Small → Primary → Images*
 */
export interface ImageSliceBannerBigXSmallPrimaryImagesItem {
  /**
   * Image field in *Image → Banner - Big x Small → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.bannerBigXSmall.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Image → Banner - Small x Big → Primary → Images*
 */
export interface ImageSliceBannerSmallXBigPrimaryImagesItem {
  /**
   * Image field in *Image → Banner - Small x Big → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.bannerSmallXBig.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Image → Banner - Auto Grid → Primary → Images*
 */
export interface ImageSliceBannerAutoGridPrimaryImagesItem {
  /**
   * Image field in *Image → Banner - Auto Grid → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.bannerAutoGrid.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Height Variant field in *Image → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image.default.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<"default" | "auto" | "fixed", "filled">;

  /**
   * Height field in *Image → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: image.default.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Smart → Primary*
 */
export interface ImageSliceSmartPrimary {
  /**
   * Images field in *Image → Smart → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.smart.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<ImageSliceSmartPrimaryImagesItem>>;

  /**
   * Layouts field in *Image → Smart → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.smart.primary.layouts[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  layouts: prismic.GroupField<Simplify<ImageSliceSmartPrimaryLayoutsItem>>;
}

/**
 * Smart variation for Image Slice
 *
 * - **API ID**: `smart`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceSmart = prismic.SharedSliceVariation<
  "smart",
  Simplify<ImageSliceSmartPrimary>,
  never
>;

/**
 * Primary content in *Image → Native → Primary*
 */
export interface ImageSliceNativePrimary {
  /**
   * Image field in *Image → Native → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.native.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Native variation for Image Slice
 *
 * - **API ID**: `native`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceNative = prismic.SharedSliceVariation<
  "native",
  Simplify<ImageSliceNativePrimary>,
  never
>;

/**
 * Primary content in *Image → Banner - Small x Big x Small → Primary*
 */
export interface ImageSliceBannerSmallXBigXSmallPrimary {
  /**
   * Images field in *Image → Banner - Small x Big x Small → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.bannerSmallXBigXSmall.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliceBannerSmallXBigXSmallPrimaryImagesItem>
  >;

  /**
   * Height Variant field in *Image → Banner - Small x Big x Small → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image.bannerSmallXBigXSmall.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<"default" | "auto" | "fixed", "filled">;

  /**
   * Height field in *Image → Banner - Small x Big x Small → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: image.bannerSmallXBigXSmall.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Banner - Small x Big x Small variation for Image Slice
 *
 * - **API ID**: `bannerSmallXBigXSmall`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBannerSmallXBigXSmall = prismic.SharedSliceVariation<
  "bannerSmallXBigXSmall",
  Simplify<ImageSliceBannerSmallXBigXSmallPrimary>,
  never
>;

/**
 * Primary content in *Image → Banner - Big x Small → Primary*
 */
export interface ImageSliceBannerBigXSmallPrimary {
  /**
   * Images field in *Image → Banner - Big x Small → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.bannerBigXSmall.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliceBannerBigXSmallPrimaryImagesItem>
  >;

  /**
   * Height Variant field in *Image → Banner - Big x Small → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image.bannerBigXSmall.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<"default" | "auto" | "fixed", "filled">;

  /**
   * Height field in *Image → Banner - Big x Small → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: image.bannerBigXSmall.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Banner - Big x Small variation for Image Slice
 *
 * - **API ID**: `bannerBigXSmall`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBannerBigXSmall = prismic.SharedSliceVariation<
  "bannerBigXSmall",
  Simplify<ImageSliceBannerBigXSmallPrimary>,
  never
>;

/**
 * Primary content in *Image → Banner - Small x Big → Primary*
 */
export interface ImageSliceBannerSmallXBigPrimary {
  /**
   * Images field in *Image → Banner - Small x Big → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.bannerSmallXBig.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliceBannerSmallXBigPrimaryImagesItem>
  >;

  /**
   * Height Variant field in *Image → Banner - Small x Big → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image.bannerSmallXBig.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<"default" | "auto" | "fixed", "filled">;

  /**
   * Height field in *Image → Banner - Small x Big → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: image.bannerSmallXBig.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Banner - Small x Big variation for Image Slice
 *
 * - **API ID**: `bannerSmallXBig`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBannerSmallXBig = prismic.SharedSliceVariation<
  "bannerSmallXBig",
  Simplify<ImageSliceBannerSmallXBigPrimary>,
  never
>;

/**
 * Primary content in *Image → Banner - Auto Grid → Primary*
 */
export interface ImageSliceBannerAutoGridPrimary {
  /**
   * Images field in *Image → Banner - Auto Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.bannerAutoGrid.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliceBannerAutoGridPrimaryImagesItem>
  >;

  /**
   * Height Variant field in *Image → Banner - Auto Grid → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image.bannerAutoGrid.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<"default" | "auto" | "fixed", "filled">;

  /**
   * Height field in *Image → Banner - Auto Grid → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: image.bannerAutoGrid.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Banner - Auto Grid variation for Image Slice
 *
 * - **API ID**: `bannerAutoGrid`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBannerAutoGrid = prismic.SharedSliceVariation<
  "bannerAutoGrid",
  Simplify<ImageSliceBannerAutoGridPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation =
  | ImageSliceDefault
  | ImageSliceSmart
  | ImageSliceNative
  | ImageSliceBannerSmallXBigXSmall
  | ImageSliceBannerBigXSmall
  | ImageSliceBannerSmallXBig
  | ImageSliceBannerAutoGrid;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Item in *MegaHero → Default → Primary → Items*
 */
export interface MegaHeroSliceDefaultPrimaryItemsItem {
  /**
   * Project field in *MegaHero → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_hero.default.primary.items[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * Project Video field in *MegaHero → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: mega_hero.default.primary.items[].project_video
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  project_video: prismic.SelectField<"default" | "alternative", "filled">;

  /**
   * Bypass Video field in *MegaHero → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_hero.default.primary.items[].bypass_video
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bypass_video: prismic.KeyTextField;

  /**
   * Bypass Video Slogan field in *MegaHero → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Only applicable if bypass video inserted
   * - **API ID Path**: mega_hero.default.primary.items[].bypass_video_slogan
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bypass_video_slogan: prismic.RichTextField;

  /**
   * Bypass Video Label Tag field in *MegaHero → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Only applicable if bypass video inserted
   * - **API ID Path**: mega_hero.default.primary.items[].bypass_video_label_tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bypass_video_label_tag: prismic.KeyTextField;

  /**
   * Bypass Video Label Name field in *MegaHero → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Only applicable if bypass video inserted
   * - **API ID Path**: mega_hero.default.primary.items[].bypass_video_label_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bypass_video_label_name: prismic.KeyTextField;

  /**
   * Autoplay field in *MegaHero → Default → Primary → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: mega_hero.default.primary.items[].autoplay
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  autoplay: prismic.BooleanField;

  /**
   * Timestamp Start field in *MegaHero → Default → Primary → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_hero.default.primary.items[].timestamp_start
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  timestamp_start: prismic.NumberField;
}

/**
 * Primary content in *MegaHero → Default → Primary*
 */
export interface MegaHeroSliceDefaultPrimary {
  /**
   * Slogan field in *MegaHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_hero.default.primary.slogan
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slogan: prismic.RichTextField;

  /**
   * Items field in *MegaHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_hero.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<MegaHeroSliceDefaultPrimaryItemsItem>>;

  /**
   * Link field in *MegaHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Label field in *MegaHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_hero.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Default variation for MegaHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MegaHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MegaHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MegaHero*
 */
type MegaHeroSliceVariation = MegaHeroSliceDefault;

/**
 * MegaHero Shared Slice
 *
 * - **API ID**: `mega_hero`
 * - **Description**: MegaHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MegaHeroSlice = prismic.SharedSlice<
  "mega_hero",
  MegaHeroSliceVariation
>;

/**
 * Item in *Nav → Default → Primary → Links*
 */
export interface NavSliceDefaultPrimaryLinksItem {
  /**
   * Label field in *Nav → Default → Primary → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.default.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Nav → Default → Primary → Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<"category" | "page" | "project">;
}

/**
 * Primary content in *Nav → Default → Primary*
 */
export interface NavSliceDefaultPrimary {
  /**
   * Links field in *Nav → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for Nav Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Nav*
 */
type NavSliceVariation = NavSliceDefault;

/**
 * Nav Shared Slice
 *
 * - **API ID**: `nav`
 * - **Description**: Nav
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavSlice = prismic.SharedSlice<"nav", NavSliceVariation>;

/**
 * Item in *ProjectGallery → Default → Primary → Projects*
 */
export interface ProjectGallerySliceDefaultPrimaryProjectsItem {
  /**
   * Project field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * Project Video field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: project_gallery.default.primary.projects[].project_video
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  project_video: prismic.SelectField<"default" | "alternative", "filled">;

  /**
   * Timestamp Start field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[].timestamp_start
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  timestamp_start: prismic.NumberField;
}

/**
 * Item in *ProjectGallery → Gallery - Small x Big → Primary → Projects*
 */
export interface ProjectGallerySliceGallerySmallXBigPrimaryProjectsItem {
  /**
   * Project field in *ProjectGallery → Gallery - Small x Big → Primary → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.gallerySmallXBig.primary.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * Project Video field in *ProjectGallery → Gallery - Small x Big → Primary → Projects*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: project_gallery.gallerySmallXBig.primary.projects[].project_video
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  project_video: prismic.SelectField<"default" | "alternative", "filled">;

  /**
   * Timestamp Start field in *ProjectGallery → Gallery - Small x Big → Primary → Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.gallerySmallXBig.primary.projects[].timestamp_start
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  timestamp_start: prismic.NumberField;
}

/**
 * Item in *ProjectGallery → Gallery - Big x Small → Primary → Projects*
 */
export interface ProjectGallerySliceGalleryBigXSmallPrimaryProjectsItem {
  /**
   * Project field in *ProjectGallery → Gallery - Big x Small → Primary → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.galleryBigXSmall.primary.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * Project Video field in *ProjectGallery → Gallery - Big x Small → Primary → Projects*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: project_gallery.galleryBigXSmall.primary.projects[].project_video
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  project_video: prismic.SelectField<"default" | "alternative", "filled">;

  /**
   * Timestamp Start field in *ProjectGallery → Gallery - Big x Small → Primary → Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.galleryBigXSmall.primary.projects[].timestamp_start
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  timestamp_start: prismic.NumberField;
}

/**
 * Item in *ProjectGallery → Gallery - Small x Big x Small → Primary → Projects*
 */
export interface ProjectGallerySliceGallerySmallXBigXSmallPrimaryProjectsItem {
  /**
   * Project field in *ProjectGallery → Gallery - Small x Big x Small → Primary → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.gallerySmallXBigXSmall.primary.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * Project Video field in *ProjectGallery → Gallery - Small x Big x Small → Primary → Projects*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: project_gallery.gallerySmallXBigXSmall.primary.projects[].project_video
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  project_video: prismic.SelectField<"default" | "alternative", "filled">;

  /**
   * Timestamp Start field in *ProjectGallery → Gallery - Small x Big x Small → Primary → Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.gallerySmallXBigXSmall.primary.projects[].timestamp_start
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  timestamp_start: prismic.NumberField;
}

/**
 * Item in *ProjectGallery → Gallery - Big x Small x Big → Primary → Projects*
 */
export interface ProjectGallerySliceGalleryBigXSmallXBigPrimaryProjectsItem {
  /**
   * Project field in *ProjectGallery → Gallery - Big x Small x Big → Primary → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.galleryBigXSmallXBig.primary.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * Project Video field in *ProjectGallery → Gallery - Big x Small x Big → Primary → Projects*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: project_gallery.galleryBigXSmallXBig.primary.projects[].project_video
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  project_video: prismic.SelectField<"default" | "alternative", "filled">;

  /**
   * Timestamp Start field in *ProjectGallery → Gallery - Big x Small x Big → Primary → Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.galleryBigXSmallXBig.primary.projects[].timestamp_start
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  timestamp_start: prismic.NumberField;
}

/**
 * Primary content in *ProjectGallery → Default → Primary*
 */
export interface ProjectGallerySliceDefaultPrimary {
  /**
   * Projects field in *ProjectGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<
    Simplify<ProjectGallerySliceDefaultPrimaryProjectsItem>
  >;

  /**
   * Gutter field in *ProjectGallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: tiny
   * - **API ID Path**: project_gallery.default.primary.gutter
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  gutter: prismic.SelectField<"tiny" | "small", "filled">;
}

/**
 * Default variation for ProjectGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectGallerySliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProjectGallery → Gallery - Small x Big → Primary*
 */
export interface ProjectGallerySliceGallerySmallXBigPrimary {
  /**
   * Projects field in *ProjectGallery → Gallery - Small x Big → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.gallerySmallXBig.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<
    Simplify<ProjectGallerySliceGallerySmallXBigPrimaryProjectsItem>
  >;

  /**
   * Gutter field in *ProjectGallery → Gallery - Small x Big → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: tiny
   * - **API ID Path**: project_gallery.gallerySmallXBig.primary.gutter
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  gutter: prismic.SelectField<"tiny" | "small", "filled">;
}

/**
 * Gallery - Small x Big variation for ProjectGallery Slice
 *
 * - **API ID**: `gallerySmallXBig`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectGallerySliceGallerySmallXBig = prismic.SharedSliceVariation<
  "gallerySmallXBig",
  Simplify<ProjectGallerySliceGallerySmallXBigPrimary>,
  never
>;

/**
 * Primary content in *ProjectGallery → Gallery - Big x Small → Primary*
 */
export interface ProjectGallerySliceGalleryBigXSmallPrimary {
  /**
   * Projects field in *ProjectGallery → Gallery - Big x Small → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.galleryBigXSmall.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<
    Simplify<ProjectGallerySliceGalleryBigXSmallPrimaryProjectsItem>
  >;

  /**
   * Gutter field in *ProjectGallery → Gallery - Big x Small → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: tiny
   * - **API ID Path**: project_gallery.galleryBigXSmall.primary.gutter
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  gutter: prismic.SelectField<"tiny" | "small", "filled">;
}

/**
 * Gallery - Big x Small variation for ProjectGallery Slice
 *
 * - **API ID**: `galleryBigXSmall`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectGallerySliceGalleryBigXSmall = prismic.SharedSliceVariation<
  "galleryBigXSmall",
  Simplify<ProjectGallerySliceGalleryBigXSmallPrimary>,
  never
>;

/**
 * Primary content in *ProjectGallery → Gallery - Small x Big x Small → Primary*
 */
export interface ProjectGallerySliceGallerySmallXBigXSmallPrimary {
  /**
   * Projects field in *ProjectGallery → Gallery - Small x Big x Small → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.gallerySmallXBigXSmall.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<
    Simplify<ProjectGallerySliceGallerySmallXBigXSmallPrimaryProjectsItem>
  >;

  /**
   * Gutter field in *ProjectGallery → Gallery - Small x Big x Small → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: tiny
   * - **API ID Path**: project_gallery.gallerySmallXBigXSmall.primary.gutter
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  gutter: prismic.SelectField<"tiny" | "small", "filled">;
}

/**
 * Gallery - Small x Big x Small variation for ProjectGallery Slice
 *
 * - **API ID**: `gallerySmallXBigXSmall`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectGallerySliceGallerySmallXBigXSmall =
  prismic.SharedSliceVariation<
    "gallerySmallXBigXSmall",
    Simplify<ProjectGallerySliceGallerySmallXBigXSmallPrimary>,
    never
  >;

/**
 * Primary content in *ProjectGallery → Gallery - Big x Small x Big → Primary*
 */
export interface ProjectGallerySliceGalleryBigXSmallXBigPrimary {
  /**
   * Projects field in *ProjectGallery → Gallery - Big x Small x Big → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.galleryBigXSmallXBig.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<
    Simplify<ProjectGallerySliceGalleryBigXSmallXBigPrimaryProjectsItem>
  >;

  /**
   * Gutter field in *ProjectGallery → Gallery - Big x Small x Big → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: tiny
   * - **API ID Path**: project_gallery.galleryBigXSmallXBig.primary.gutter
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  gutter: prismic.SelectField<"tiny" | "small", "filled">;
}

/**
 * Gallery - Big x Small x Big variation for ProjectGallery Slice
 *
 * - **API ID**: `galleryBigXSmallXBig`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectGallerySliceGalleryBigXSmallXBig =
  prismic.SharedSliceVariation<
    "galleryBigXSmallXBig",
    Simplify<ProjectGallerySliceGalleryBigXSmallXBigPrimary>,
    never
  >;

/**
 * Slice variation for *ProjectGallery*
 */
type ProjectGallerySliceVariation =
  | ProjectGallerySliceDefault
  | ProjectGallerySliceGallerySmallXBig
  | ProjectGallerySliceGalleryBigXSmall
  | ProjectGallerySliceGallerySmallXBigXSmall
  | ProjectGallerySliceGalleryBigXSmallXBig;

/**
 * ProjectGallery Shared Slice
 *
 * - **API ID**: `project_gallery`
 * - **Description**: ProjectGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectGallerySlice = prismic.SharedSlice<
  "project_gallery",
  ProjectGallerySliceVariation
>;

/**
 * Primary content in *Spacer → Default → Primary*
 */
export interface SpacerSliceDefaultPrimary {
  /**
   * Size field in *Spacer → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: small
   * - **API ID Path**: spacer.default.primary.size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<"small" | "medium" | "big", "filled">;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpacerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type SpacerSliceVariation = SpacerSliceDefault;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: Spacer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSlice = prismic.SharedSlice<"spacer", SpacerSliceVariation>;

/**
 * Primary content in *Standout → Default → Primary*
 */
export interface StandoutSliceDefaultPrimary {
  /**
   * Text field in *Standout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: standout.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Link field in *Standout → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: standout.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Label field in *Standout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: standout.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Color field in *Standout → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: standout.default.primary.color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;
}

/**
 * Default variation for Standout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StandoutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StandoutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Standout*
 */
type StandoutSliceVariation = StandoutSliceDefault;

/**
 * Standout Shared Slice
 *
 * - **API ID**: `standout`
 * - **Description**: Standout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StandoutSlice = prismic.SharedSlice<
  "standout",
  StandoutSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Text → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Height Variant field in *Text → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: text_with_image.default.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<
    "default" | "auto" | "fixed" | "double" | "full_screen",
    "filled"
  >;

  /**
   * Height field in *Text → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: text_with_image.default.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Text Half - Image Half → Primary*
 */
export interface TextWithImageSliceTextLeftImageRightPrimary {
  /**
   * Text field in *Text → Text Half - Image Half → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.textLeftImageRight.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Text → Text Half - Image Half → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.textLeftImageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Height Variant field in *Text → Text Half - Image Half → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: text_with_image.textLeftImageRight.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<
    "default" | "auto" | "fixed" | "double" | "full_screen",
    "filled"
  >;

  /**
   * Height field in *Text → Text Half - Image Half → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: text_with_image.textLeftImageRight.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Text Half - Image Half variation for Text Slice
 *
 * - **API ID**: `textLeftImageRight`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceTextLeftImageRight = prismic.SharedSliceVariation<
  "textLeftImageRight",
  Simplify<TextWithImageSliceTextLeftImageRightPrimary>,
  never
>;

/**
 * Primary content in *Text → Image Half - Text Half → Primary*
 */
export interface TextWithImageSliceImageLeftTextRightPrimary {
  /**
   * Text field in *Text → Image Half - Text Half → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.imageLeftTextRight.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Text → Image Half - Text Half → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.imageLeftTextRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Height Variant field in *Text → Image Half - Text Half → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: text_with_image.imageLeftTextRight.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<
    "default" | "auto" | "fixed" | "double" | "full_screen",
    "filled"
  >;

  /**
   * Height field in *Text → Image Half - Text Half → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: text_with_image.imageLeftTextRight.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Image Half - Text Half variation for Text Slice
 *
 * - **API ID**: `imageLeftTextRight`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceImageLeftTextRight = prismic.SharedSliceVariation<
  "imageLeftTextRight",
  Simplify<TextWithImageSliceImageLeftTextRightPrimary>,
  never
>;

/**
 * Primary content in *Text → Text Large - Image Small → Primary*
 */
export interface TextWithImageSliceTextLargeImageSmallPrimary {
  /**
   * Text field in *Text → Text Large - Image Small → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.textLargeImageSmall.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Text → Text Large - Image Small → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.textLargeImageSmall.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Height Variant field in *Text → Text Large - Image Small → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: text_with_image.textLargeImageSmall.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<
    "default" | "auto" | "fixed" | "double" | "full_screen",
    "filled"
  >;

  /**
   * Height field in *Text → Text Large - Image Small → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: text_with_image.textLargeImageSmall.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Text Large - Image Small variation for Text Slice
 *
 * - **API ID**: `textLargeImageSmall`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceTextLargeImageSmall =
  prismic.SharedSliceVariation<
    "textLargeImageSmall",
    Simplify<TextWithImageSliceTextLargeImageSmallPrimary>,
    never
  >;

/**
 * Primary content in *Text → Image Small - Text Large → Primary*
 */
export interface TextWithImageSliceImageSmallTextLargePrimary {
  /**
   * Text field in *Text → Image Small - Text Large → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.imageSmallTextLarge.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Text → Image Small - Text Large → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.imageSmallTextLarge.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Height Variant field in *Text → Image Small - Text Large → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: text_with_image.imageSmallTextLarge.primary.height_variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height_variant: prismic.SelectField<
    "default" | "auto" | "fixed" | "double" | "full_screen",
    "filled"
  >;

  /**
   * Height field in *Text → Image Small - Text Large → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Only valid if variant fixed selected
   * - **API ID Path**: text_with_image.imageSmallTextLarge.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Image Small - Text Large variation for Text Slice
 *
 * - **API ID**: `imageSmallTextLarge`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceImageSmallTextLarge =
  prismic.SharedSliceVariation<
    "imageSmallTextLarge",
    Simplify<TextWithImageSliceImageSmallTextLargePrimary>,
    never
  >;

/**
 * Slice variation for *Text*
 */
type TextWithImageSliceVariation =
  | TextWithImageSliceDefault
  | TextWithImageSliceTextLeftImageRight
  | TextWithImageSliceImageLeftTextRight
  | TextWithImageSliceTextLargeImageSmall
  | TextWithImageSliceImageSmallTextLarge;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Playback Id field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.playback_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  playback_id: prismic.KeyTextField;

  /**
   * Placeholder Timestamp field in *Video → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.placeholder_timestamp
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  placeholder_timestamp: prismic.NumberField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategoryDocument,
      CategoryDocumentData,
      CategoryDocumentDataSlicesSlice,
      ClientDocument,
      ClientDocumentData,
      ClientDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      NotFoundDocument,
      NotFoundDocumentData,
      NotFoundDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocumentDataFooterItem,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataCategoriesItem,
      ProjectDocumentDataCreditsItem,
      ProjectDocumentDataSlicesSlice,
      ProjectDocumentDataFooterItem,
      RedirectsDocument,
      RedirectsDocumentData,
      RedirectsDocumentDataRedirectsItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSocialLinksItem,
      SettingsDocumentDataFooterBackToLinkItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryContactsItem,
      AboutSliceDefaultPrimaryFooterItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceSmartPrimaryImagesItem,
      ImageSliceSmartPrimaryLayoutsItem,
      ImageSliceSmartPrimary,
      ImageSliceNativePrimary,
      ImageSliceBannerSmallXBigXSmallPrimaryImagesItem,
      ImageSliceBannerSmallXBigXSmallPrimary,
      ImageSliceBannerBigXSmallPrimaryImagesItem,
      ImageSliceBannerBigXSmallPrimary,
      ImageSliceBannerSmallXBigPrimaryImagesItem,
      ImageSliceBannerSmallXBigPrimary,
      ImageSliceBannerAutoGridPrimaryImagesItem,
      ImageSliceBannerAutoGridPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceSmart,
      ImageSliceNative,
      ImageSliceBannerSmallXBigXSmall,
      ImageSliceBannerBigXSmall,
      ImageSliceBannerSmallXBig,
      ImageSliceBannerAutoGrid,
      MegaHeroSlice,
      MegaHeroSliceDefaultPrimaryItemsItem,
      MegaHeroSliceDefaultPrimary,
      MegaHeroSliceVariation,
      MegaHeroSliceDefault,
      NavSlice,
      NavSliceDefaultPrimaryLinksItem,
      NavSliceDefaultPrimary,
      NavSliceVariation,
      NavSliceDefault,
      ProjectGallerySlice,
      ProjectGallerySliceDefaultPrimaryProjectsItem,
      ProjectGallerySliceDefaultPrimary,
      ProjectGallerySliceGallerySmallXBigPrimaryProjectsItem,
      ProjectGallerySliceGallerySmallXBigPrimary,
      ProjectGallerySliceGalleryBigXSmallPrimaryProjectsItem,
      ProjectGallerySliceGalleryBigXSmallPrimary,
      ProjectGallerySliceGallerySmallXBigXSmallPrimaryProjectsItem,
      ProjectGallerySliceGallerySmallXBigXSmallPrimary,
      ProjectGallerySliceGalleryBigXSmallXBigPrimaryProjectsItem,
      ProjectGallerySliceGalleryBigXSmallXBigPrimary,
      ProjectGallerySliceVariation,
      ProjectGallerySliceDefault,
      ProjectGallerySliceGallerySmallXBig,
      ProjectGallerySliceGalleryBigXSmall,
      ProjectGallerySliceGallerySmallXBigXSmall,
      ProjectGallerySliceGalleryBigXSmallXBig,
      SpacerSlice,
      SpacerSliceDefaultPrimary,
      SpacerSliceVariation,
      SpacerSliceDefault,
      StandoutSlice,
      StandoutSliceDefaultPrimary,
      StandoutSliceVariation,
      StandoutSliceDefault,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceTextLeftImageRightPrimary,
      TextWithImageSliceImageLeftTextRightPrimary,
      TextWithImageSliceTextLargeImageSmallPrimary,
      TextWithImageSliceImageSmallTextLargePrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TextWithImageSliceTextLeftImageRight,
      TextWithImageSliceImageLeftTextRight,
      TextWithImageSliceTextLargeImageSmall,
      TextWithImageSliceImageSmallTextLarge,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
