export const ProjectHeroLinks = [
    "project.title",
    "project.description",
    "project.color",
    "project.categories",
    "project.client",
    "project.video_full",
    "project.video_full_thumbnail_bypass",
    "project.video",
    "project.video_thumbnail_time_bypass",
    "project.video_alternative",
    "project.video_short_alt_thumbnail_bypass",
    "project.project_video",
    "project.hero_format",
    "client.name",
    "category.title",
];
