import { ReactNode } from "react";

import { Params } from "next/dist/shared/lib/router/utils/route-matcher";

import { createClient } from "@/prismicio";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export async function WorkLayout({
    children,
    params,
}: {
    children: ReactNode;
    params: Params;
}) {
    const client = createClient({});

    const categories = await client.getAllByType("category", {
        lang: params.lang,
    });

    console.log(categories);
    return <div>{children}</div>;
}
