import { ReactNode } from "react";

import { Params } from "next/dist/shared/lib/router/utils/route-matcher";

import { Filter } from "@/components/filter/filter";
import { createClient } from "@/prismicio";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default async function WorkLayout({
    children,
    params,
}: {
    children: ReactNode;
    params: Params;
}) {
    const client = createClient({});

    const categories = await client.getAllByType("category", {
        lang: params.lang,
    });

    const items = categories.map((category) => ({
        label: category.data.title as string,
        value: `/work?category=${category.uid}`,
    }));

    return (
        <div>
            <Filter items={items} />
            <div>{children}</div>
        </div>
    );
}
