// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  filter: dynamic(() => import("./Nav")),
  image: dynamic(() => import("./Image")),
  mega_hero: dynamic(() => import("./MegaHero")),
  project_gallery: dynamic(() => import("./ProjectGallery")),
  spacer: dynamic(() => import("./Spacer")),
  standout: dynamic(() => import("./Standout")),
  text_with_image: dynamic(() => import("./Text")),
  video: dynamic(() => import("./Video")),
};
