import { ReactNode } from "react";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function ProjectLayout({ children }: { children: ReactNode }) {
    return <div>{children}</div>;
}
